Apprentice section finished
ioana-condrea/kotlin-coding-challenges pull request #2
Opened 2021-11-19 07:54 UTC by ioana-condrea

2021-11-24 07:57 UTC, radu-marin-sv requested changes

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/integer/fizzbuzz/challenge.kt
> +            it == 1 && it == n -> it.toString()
what's the purpose of this condition? If it is 1 and it is n, it means n is 1 :)

Also 1 and n should definitely be checked with the following rules, right?

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/integer/reverse/challenge.kt
> +    return if (i < 0) {
Kotlin math (https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.math/) might yield some nice functionality that can simplify this logic.

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/integer/reverse/challenge.kt
> +    } else s.reversed().toInt()
inconsistent formatting. Please use curly braces in if-else statements even if they are single line expressions. It makes it easier to read & debug.

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/integer/pyramidgenerator/challenge.kt
> +    (0 until n).forEach { i ->
Can you think of a way to construct the list while iterating instead of having a mutable list that you keep on appending?

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/integer/stepsgenerator/challenge.kt
> +    (0 until n).forEach { i ->
Can you think of a way to construct the list while iterating instead of having a mutable list that you keep on appending?

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/caesarcipher/challenge.kt
> +        if (asciiShifted > z) {
Could this if statement be replaced by a modulo operation instead?

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/caesarcipher/challenge.kt
> +        if (shift > (z - a + 1)) {
Could this if statement be replaced by a modulo operation instead?

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/hasrepeatedcharacter/challenge.kt
> +            if (str.filter { s -> s == c }.length > 1)
please use curly braces in if statements even if the body is a single-line statement

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/isanagram/challenge.kt
> +    return stringContent1.toLowerCase()
you can make the code more readable by splitting up your statements:
```
val sortedChars1 = stringContent1.toLowerCase()
        .toCharArray()
        .sortedArray()
val sortedChars12= stringContent2.toLowerCase()
        .toCharArray()
        .sortedArray()
return sortedChars1.contentEquals(sortedChars2)
```

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/integer/stepsgenerator/challenge.kt
> +            } else steps[i] += " "
inconsistent formatting. Please use curly braces in if-else statements even if they are single line expressions. It makes it easier to read & debug.

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/ispalindrome/permutation/challenge.kt
> +    str.forEach {
Please name 'it', this will make your code easier to read.

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/ispalindrome/permutation/challenge.kt
> +        val noChars = str.filter { c ->
Please make variable names more readable, e.g. noChars can be charOccurrences or charCount.

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/ispalindrome/permutation/challenge.kt
> +    var oneCharAllowed = false
The name of this variable is a bit vague or counter-intuitive. Shouldn't this something like: oneCharAlreadyEncountered?

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/ispalindrome/permutation/challenge.kt
> +        if (noChars > 2) return false
Please add this test:
```
@Test
    fun `"aaaa" is a palindrome`() {
        isPermutationPalindrome("aaaa") shouldBeEqualTo true
    }
```

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/ispalindrome/tolerant/challenge.kt
> +    return if (nonLettersOrDigits.length > 1 || (letters.length > 1 && digits.length > 1)) false
inconsistent formatting. Please use curly braces in if-else statements even if they are single line expressions. It makes it easier to read & debug.

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/maxchar/challenge.kt
> +    var (mostUsed, currentHighestNoTimes) = Pair(' ', 0)
hehe.. you might be overusing decomposition here, but i'll take it :)

2021-11-24 07:57 UTC, radu-marin-sv commented on src/test/kotlin/com/igorwojda/string/maxchar/challenge.kt
> +        if (noTimes > currentHighestNoTimes)
inconsistent formatting. Please use curly braces in if-else statements even if they are single line expressions. It makes it easier to read & debug.

2021-11-24 08:08 UTC, ioana-condrea commented on src/test/kotlin/com/igorwojda/integer/fizzbuzz/challenge.kt
> +            it == 1 && it == n -> it.toString()
I don't know what was the logic behind that, probably none 🥲

2021-11-26 12:29 UTC, radu-marin-sv approved these changes

2021-11-26 15:12 UTC, merged